//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace build {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class mhaagsma : global::System.Configuration.ApplicationSettingsBase {
        
        private static mhaagsma defaultInstance = ((mhaagsma)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new mhaagsma())));
        
        public static mhaagsma Default {
            get {
                return defaultInstance;
            }
        }
    }
}
